// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzrddsijzessljfzssjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6cmRkc2lqemVzc2xqZnpzc2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTA4NzYsImV4cCI6MjA2Nzg2Njg3Nn0.eDEpB-fVcVOwK1ZLMP6lWui6YESfDzJQSmV57vUoJ-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});